kind: Pod
apiVersion: v1
metadata:
  name: sidecar-pod
spec:
  
  volumes:
  - name: shared-logs
    emptyDir: {}

  containers:
  - name: main-container
    image: busybox
    command: ["sh","-c","while true; do echo 'Hello World' >> /var/log/app.log; sleep 5; done"]
    volumeMounts: 
    name: shared-logs
  
  - name: sidecar-container
    image: busybox
    command: ["sh", "-c","tail -f /var/log/app.log"]
