apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-probe
  labels:
    app: nginx
  namespace: nginx-ns

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx

  # template is written same as yaml for pods
  template:
    metadata:
      labels:
        app: nginx
    
    spec:
      conatiners:
        - name: nginx-container
          image: python:latest
          ports:
          - containerPort: 8000
          livenessProbe:
            httpGet:
            path: /
            port: 8000
          
          readinessProbe:
            httpGet:
            path: /
            port: 8000
          