# create the deployment with env variables from configmap

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostNetwork: true
      containers:
      - image: piyushsachdeva/hello-app:4.0
        name: hello-app
        # 1st way to set environment variables from configMap
        # env:
        # - name: FIRST_NAME
        #   valueFrom:
        #     configMapKeyRef:
        #       name: sample-cm
        #       key: first
        # - name: LAST_NAME
        #   valueFrom:
        #     configMapKeyRef:
        #       name: sample-cm
        #       key: last

        # 2nd way to set environment variables from configMap
        envFrom:
        - configMapRef:
            name: configmap-example

        ports:
        - containerPort: 3000

