apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  username: bXl1c2Vy
  password: bXlwYXNzd29yZA==  # base64 encoded value encode before writing in yaml


# secret in deployment
env:
 - name: DB_PASSWORD
valueFrom:
  secretKeyRef:
  name: my-secret
  key: password

# secret in pod
env:
 - name: DB_USERNAME
   valueFrom:
     secretKeyRef:
       name: my-secret
       key: username